### PR TITLE
Also exclude libwine.so.1

### PR DESCRIPTION
**Pull request by tresf**
Per LMMS/lmms#3688, use the system provided version, if available.

This PR prevents a broken wine configuration.  If shipping a library, (e.g.) `foo.exe.so`, which links against `libwine.so.1`, `linuxdeployqt` will bundle `libwine.so.1`.  Since `libwine.so.1` depends on a functioning Wine environment (it doesn't appear to link and thus doesn't bundle libraries such as `ntdll.dll.so`) it shouldn't be bundled.

This topic is discussed a bit further here: https://forum.winehq.org/viewtopic.php?f=8&t=28984#p110994

I see there are a few Wine projects that are bundled into `.AppImage`s, but I'm going to make an educated guess and assume none of them are using `linuxdeployqt` to do so.

From discussions downstream, I do not expect this to be merged, but it can at least provide a [workable fork](https://github.com/tresf/linuxdeployqt/releases/tag/continuous) for others experiencing the same problem.

### CODE REVIEW

**Comment by probonopd** [comment]
As per my [other comment](https://github.com/LMMS/lmms/pull/3688#issuecomment-318738681), I think that this case is rather a very specific exception for the package you are working on than a general issue. Do you agree?

**Comment by tresf** [comment]
> As per my other comment, I think that this case is rather a very specific exception for the package you are working on than a general issue. Do you agree?

I've spent a full work week worth of hours trying to wrap my head around what portion of `linuxdeployqt` is assuming I want this library bundled.  Something is making an assumption somewhere as when the offending `foo.exe.so` is NOT provided as an `-executable=`, it still gets crawled and the `libwine.so.1` dependency still gets injected.

If the "please don't bundle stuff I didn't ask for" problem goes away, this all becomes moot.

In regards to the normalcy of this problem.. This question will likely never get an answer.  Very few native linux projects do RPC against Windows executables and for those that do, I don't think they'd want to ship a full-blown Wine version, and in the rare case that they do, I don't see them using `linuxdeployqt` to do it.

First, there's the whole `multilib` problem which prevent the 32-bit wine executables from even running on some systems.

Second, `ldd` tool doesn't really search and bundle wine anyhow, so `linuxdeployqt` can't really be used to bundle wine, at least not in its current state.  This library seems like it will just cause problems.

So, in a hypothetical world where someone is using `linuxdeployqt` combined with a wine installation, is `libwine.so.1` being blacklisted going to cause problems?  Hard to make an educated guess, but my feeling is they'd use a custom `LD_LIBRARY_PATH` to pick up the bottle anyhow and the `libwine.so.1` would require some further hacks to locate `ntdll.dll.so` and friends anyway, so this would be a minor inconvenience.

Again, this all goes away if I can just find a way to skip this from being included.  I'm about ready to move it out of the `lib` folder entirely, but now we're changing C++ calls due to a nuance with a packaging tool, no?

**Comment by TheAssassin** [comment]
Splitting up the linuxdeployqt call should be a sufficient workaround.

First call linuxdeployqt to create the AppDir, then fix the libraries (`rm` is your friend), and then call appimagetool manually. Yes, that's three steps instead of one, but this gives you the control you need.

**Comment by probonopd** [comment]
`linuxdeployqt` is intended to be a simple tool with only as many options as are absolutely necessary. For more advanced/manual use cases, as @TheAssassin said it is advisable to manually edit/optimize the AppDir, and then generate an AppImage from it using the lower-level `appimagetool`, which does not touch the contents of the AppDir.

**Pull request closed without merging**
