### PR TITLE
Add exclude list messages and tests in project

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by TheAssassin** [comment]
Related to #273.

Does the build fail if the called script fails?

**Comment by probonopd** [comment]
Can we please make it so that as @TheAssassin described in https://github.com/probonopd/linuxdeployqt/issues/274

> The build system should, while configuring, or ideally on every build, always call this script and try to update the source file. If the script fails, there's an automatic "fallback" mechanism to use the old data.

**Comment by TheAssassin** [comment]
@patrickelectric that seems a bit hackish, to be honest. When trying to implement #274, I think I will need a _real_ error check, like checking the exit code of the commands called.

**Comment by patrickelectric** [comment]
@TheAssassin, AFAIK qmake $$system will only return strings and not system error code. What It's possible to do is to check if such programs exist inside the shell script, but it will return an error string or a empty string for that, and then to be handle by qmake.

**Comment by patrickelectric** [comment]
@probonopd this is to fix #273 and not #274, if such thing need to be done, it'll be in another PR. I can't solve all issues if I'm not aware. I don't know how this project is handle but it's pretty confuse with a various issues for the same thing...

**Comment by probonopd** [comment]
Good that you are aware of both issues now :-)

**Comment by TheAssassin** [comment]
@patrickelectric this doesn't fully fix #273, though, as the git commands still fail silently.

I'll try to add the missing bits to this PR tonight.

**Comment by TheAssassin** [comment]
I decided to allow failures of git commands for now, as it's really complicated to check the exit code of commands in qmake. In CMake, failing git commands will cause CMake to fail the configuration.

In its current state, this PR implements #273 partially. I would merge it now, but keep #273 open until the qmake part is fixed. Maybe we find someone who _likes_ fiddling with qmake. I certainly don't.

**Comment by TheAssassin** [comment]
Thanks, @patrickelectric!

**Comment by patrickelectric** [comment]
I'm glad that this PR was useful.

**Pull request merged**
