### PR TITLE
Fix #184 segfault on multiarch systems

### LINKED ISSUE #184: Segfault since copyCopyrightFile
I believe a bug is introduced in c5ba2e7.

Using `linuxdeployqt` with the following options:

```
linuxdeployqt lmms.desktop -bundle-non-qt-libs -verbose=3 -qmake=/opt/qt58/bin/qmake
```

This bug does NOT occur if the `-bundle-non-qt-libs` is omitted.

`linuxdeployqt` succeeds if I move `dpkg` out of the way to force-skip the `copyCopyrightFile` logic.

Here's the backtrace, which I was able to gather by doing `run` and then `bt full` after running the following commmand:

```bash
gdb --args squashfs-root/usr/bin/linuxdeployqt [path-to]/lmms.desktop -bundle-non-qt-libs -verbose=3 -qmake=/opt/qt58/bin/qmake
```

```
(gdb) backtrace
#0  QtPrivate::RefCount::ref (this=0x100000000)
    at /opt/qt59/include/QtCore/qrefcount.h:55
#1  0x000000000040e3a5 in QString (other=..., this=0x7fffffffc170)
    at /opt/qt59/include/QtCore/qstring.h:907
#2  copyCopyrightFile (libPath=...) at shared.cpp:328
#3  0x000000000040f4fc in copyDylib (library=..., path=...) at shared.cpp:751
#4  0x0000000000416c1e in deployQtLibraries (libraries=..., bundlePath=..., 
    binaryPaths=..., useLoaderPath=<optimized out>) at shared.cpp:1010
#5  0x00000000004194de in deployQtLibraries (appDirPath=..., 
    additionalExecutables=..., qmake=...) at shared.cpp:1178
#6  0x0000000000407a1f in main (argc=4, argv=0x7fffffffde38) at main.cpp:398
(gdb) 
```

### PR DESCRIPTION
**Pull request by probonopd**
Thanks @tresf

### CODE REVIEW

**Comment by tresf** [comment]
I'm sorry, I closed the parent bug report before the PR was merged.  How'd I get my hands on the continuous that quickly then?

**Comment by probonopd** [comment]
https://github.com/probonopd/linuxdeployqt/releases

**Comment by tresf** [comment]
@probonopd do you upload all PRs into continuous in that fashion before they're actually merged?  What am I missing?

**Comment by probonopd** [comment]
It has been merged!

**Comment by probonopd** [comment]
PRs don't get uploaded to GitHub Releases, but branches do.

**Pull request merged**
