### PR TITLE
Move RPATH adjustment to after library bundling

### PR DESCRIPTION
**Pull request by gtalent**
Libraries found with the RPATH could not be found by the bundler because
the RPATH was getting changed before the bundling.

### CODE REVIEW

**Comment by probonopd** [comment]
Thank you very much. Do you have an example that did not work without this patch but works now?

**Comment by gtalent** [comment]
I can't share the project that this was for, but I did reproduce it here:
https://github.com/gtalent/example

**Comment by probonopd** [comment]
Thank you very much.

**Comment by M-Mueller** [comment]
This is still an issue if a library as an RPATH. For example if you have the following structure:
```
bin/foo
lib/libfoo.so
lib/libfoo/libbar.so
```
`libfoo.so` has an RPATH of `$ORIGIN/libfoo` and links against `libbar.so`.

linuxdeployqt will first set the RPATH of `libfoo.so` to `$ORIGIN` and then complain that ldd cannot find `libbar.so`. I think the order in this case should be changed as well.

**Comment by probonopd** [comment]
@M-Mueller I had _attempted_ to fix this by adding `lib/libfoo.so` to `LD_LIBRARY_PATH` in https://github.com/probonopd/linuxdeployqt/commit/9a93e030cff2cb10e9e672ebb3360d30b3099c6d but apparently it is not working. Any help appreciated.

**Pull request merged**
