### PR TITLE
Create excludelist at build time

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by TheAssassin** [comment]
This is build time, not runtime.

**Comment by TheAssassin** [comment]
Thanks, looks solid.

**Comment by patrickelectric** [comment]
Corrections done.

**Comment by TheAssassin** [comment]
Seems to work: https://travis-ci.org/probonopd/linuxdeployqt/builds/360672072#L878

**Comment by TheAssassin** [comment]
Thanks, highly appreciated.

**Comment by probonopd** [comment]
Thank you very much @patrickelectric - great job!

**Comment by probonopd** [comment]
Unfortunately this breaks on OBS, please see https://github.com/probonopd/linuxdeployqt/issues/272 and fix this, otherwise I need to revert.

**Pull request merged**
