### PR TITLE
added -ignore-unknownlib flag

### PR DESCRIPTION
**Pull request by EndrII**
I think that the program should not end with code 1, in case it did not find any of the libraries in the system.
therefore I add a flag that ignores this.

### CODE REVIEW

**Comment by probonopd** [comment]
Why do you think this is a good idea? After all, it means that something is broken if not all libraries are found by `ldd`...

**Comment by EndrII** [comment]
this flag is needed in those situations when some libraries have dependencies that are not used by the application at all.
for example:
my application uses sqlite
but because of the SQL plug-in dependencies require mysql although it is not needed and it is not in the system.

**Comment by probonopd** [comment]
In this case, why don't you just remove the MySQL plugin from the bundle then? Shipping plugins with unresolved dependencies is not the solution to this issue.

**Comment by EndrII** [comment]
okay, I'll make a new deployer, devoid of stupid flaws.

**Comment by probonopd** [comment]
So you need to:
* Run `linuxdeployqt -bundle-non-qt-libs` - this will give you an AppDir
* Delete the Qt plugins and libraries from the AppDir which you think are not needed
* Convert the AppDir into an AppImage manually using `appimagetool`

Since a copy of `appimagetool` is included in the `linuxdeployqt` AppImage, you can use it similar to what I have done here:

https://github.com/probonopd/audacity/blob/b17a7015e40f67ebfb7779edf2b10da9a0cc45b5/.travis.yml#L64-L67

Please let me know if something is unclear.

**Comment by EndrII** [comment]
thanks, but I've already solved my problem. [my splution](https://github.com/QuasarApp/Console-QtDeployer)

**Comment by TheAssassin** [comment]
@probonopd as @EndrII pointed out, the problem is that one of the libraries linuxdeployqt wants to deploy links to libraries which are not installed. He doesn't want to install bloat.

@EndrII what you suggested is the "big wooden hammer method". You could simply use the manual exclude feature to exclude the offending libs.

**Comment by TheAssassin** [comment]
@EndrII now you created a https://xkcd.com/927/ situation...

**Pull request closed without merging**
