### PR TITLE
Add -qtlibinfix support in order to precise the libinfix set for a custom Qt distribution. Without this option, linuxdeployqt is not able to look at the Qt plugins directory.

### PR DESCRIPTION
**Pull request by tcladet**
In our company, we built a custom Qt distribution where all .so libraries are suffixed. This patch provides the ability to set this suffix in order to help linuxqtdeploy to find Qt plugins directory. Without it, **deploymentInfo.qtPath** struct field remains empty and **deployPlugins()** function is not called.
The argument exposed is **-qtlibinfix** like the Qt build chain.

### CODE REVIEW

**Comment by probonopd** [comment]
linuxdeployqt is supposed to figure out the path to Qt from `-qmake=<path>            : The qmake executable to use.`

Does that not work for you?

**Comment by tcladet** [comment]
Sorry for the **BIG** delay... We are using the -qmake option, but our libraries are suffixed: **libQt5CoreCustom.so** (for example). This suffix can be set on Qt build chain (-qtlibinfix). The objective in this pull request is to add this information in linuxdeployqt to help it to detect Qt5Core.so and Qt5Widgets.so libraries.

**Comment by probonopd** [comment]
Thanks @tcladet. Could you please expand upon the documentation and include an example as to what this is useful for (mentioning the `libQt5CoreCustom.so` example)?

**Comment by tcladet** [comment]
Documentation is ready.

**Comment by probonopd** [comment]
Thank you @tcladet

**Comment by probonopd** [comment]
Now I'd be curious, is your AppImage that is using a custom Qt distribution available for download somewhere? I've never seen something like that in the wild.

**Comment by tcladet** [comment]
I understand your surprise :) the application is a Commercial one and we only use `linuxdeployqt` to prepare the distribution. We don't generate `app/dmg` AppImage files. This technique is used to avoid clashes between multiple softwares that communicate together and embed their own version of Qt.

**Pull request merged**
