### PR TITLE
Change Qt WebEngine resources path

### PR DESCRIPTION
**Pull request by atehxx**
Fixed few paths to Web Engine resources as where they seem to be in 5.7.1

### CODE REVIEW

**Comment by probonopd** [comment]
With which distribution of Qt did you test `../resources/qtwebengine_resources.pak`?

Are you sure `../resources/qtwebengine_resources.pak` is the correct path for most/all Qt distributions/packages of Qt? Or could it be that some still use `../resources/qtwebengine_resources.pak`? Maybe we should search the directory tree in a bit more flexible way rather than just hardcoding one path.

Or possibly we can read out the correct path somehow from the detected Qt installation?

**Comment by atehxx** [comment]
This path is correct for 5.7.1 from Qt company as on my PC. No idea for other releases tho.
I also found this that confirms paths: [https://www.archlinux.org/packages/extra/x86_64/qt5-webengine/files/](https://www.archlinux.org/packages/extra/x86_64/qt5-webengine/files/)

No idea how to always find best path, other than scanning all sub directories of Qt. At least we know file names.

**Comment by probonopd** [comment]
According to the documentation, 

> Qt WebEngine requires the following resource files:
> 
> qtwebengine_resources.pak contains the resources needed by Chromium.
> qtwebengine_devtools_resources.pak contains tools for remote debugging.
> qtwebengine_resources_100p.pak contains images suitable for low resolution displays.
> qtwebengine_resources_200p.pak contains images suitable for high DPI displays.
> icudtl.dat provides support for International Components for Unicode (ICU). It is the Chromium version of ICU, which is not needed if Qt WebEngine was configured to use the system ICU.
Resources are searched from the following locations:
>
> On Linux and Windows: the resources directory in the directory specified by QLibraryInfo::location(QLibraryInfo::DataPath)

So the question is, how can we get `QLibraryInfo::location(QLibraryInfo::DataPath)` from the current installation of Qt.

**Comment by probonopd** [comment]
Currently we are using `QSet<QString> allRPaths = getBinaryRPaths(applicationBundle.binaryPath, true);` so I think it would be just a matter of accessing `QLibraryInfo::location(QLibraryInfo::DataPath)` and `QLibraryInfo::location(QLibraryInfo::TranslationsPath)` in a similar way. Can you give it a try and see if it works?

**Comment by atehxx** [comment]
`QLibraryInfo::DataPath` points to root Qt folder, so we still need to add ./resources/ to it - also as mentioned in documentation. And whole change here is that in your original code you were looking for those files in ./libexec and not in ./resources.
Also, `QLibraryInfo::location` gives the same results as you already query from `qmake -query` into `qtToBeBundledInfo` in shared.cpp so maybe let's stick to one way.
Still, it's needed to change way of getting this path, as currently there is `../` from plugins directory - which might not be in root Qt directory. I'm working on it. 
Also, I'm not familiar with github nor git - is it possible to make more edits to this pull request, or I need to make new one later and what happens then to this one?

**Comment by probonopd** [comment]
Thanks for the clarification, makes sense. I just can't remember why I was using libexec - might well be because in _some_ Qt installation I saw the files there, but cannot say for sure anymore.
You can add edits to the existing Pull Request by doing additional commits to your `patch-1` branch. They will then be appended to this Pull Request.

**Comment by probonopd** [comment]
@atehxx are you still on this?

See this discussion here:
https://github.com/probonopd/linuxdeployqt/issues/57

**Comment by atehxx** [comment]
Hi!
I finally got some time to finish those improvements.
As mentioned earlier source paths are taken from used Qt installation (other method than `QLibraryInfo::location` - just used what was already in code.
There was also further problem to this, as turns out browser process didn't use the qt.conf next to main executable so it was using default paths - resulting in still looking for resources in directory where Qt was installed (for tests - after using linuxdeployqt (twice... as once is not doing all the work somehow) I change the name of original Qt directory so I make sure my app uses only local files).
The resolution to this seem to be another qt.conf file next to browser process executable, which points `Prefix` config option to parent directory - main app directory. This is now added also.
I hope this finishes that task :)

**Pull request merged**
