### PR TITLE
Added important info on how to get icon themes working

### PR DESCRIPTION
**Pull request by DougBeney**

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @DougBeney, can you provide before/after screenshots?

**Comment by DougBeney** [comment]
In this readme or to help you understand what I mean? If the ladder, here you go.

**After**: screenshot

The Before is the same thing except no icons in the menu items, in the top-left of the screen you can see my blue little icon. That wouldn't be there in the Before. In your dock/window-list, the icon would not display.

**Comment by probonopd** [comment]
Wow, so without this plugin there are no icons? Interesting. Do you know whether there is a way to automatically find out whether the application uses this plugin's functionality and hence should be bundled?

**Comment by probonopd** [comment]
> Btw, I released my Qt app yesterday that uses LinuxDeployQt. 

Cool. There are still minor issues with that AppImage, please see https://github.com/AppImage/appimage.github.io/pull/859

**Pull request merged**
