### PR TITLE
Mention apkstudio in list of projects.

### PR DESCRIPTION
**Pull request by vaibhavpandeyvpz**

### CODE REVIEW

**Comment by probonopd** [comment]
Thank you @vaibhavpandeyvpz

**Comment by probonopd** [comment]
Hi @vaibhavpandeyvpz,

when running the AppImage, getting

> You need to download some 3rd-party applications/files and place them in proper directory for APK Studio to work. 



All the things mentioned in https://github.com/vaibhavpandeyvpz/apkstudio#requirements should be bundled inside the AppImage, so that the user does not need to download additional things, just the AppImage.

Reference:
https://github.com/AppImage/appimage.github.io/pull/458 (this has been preventing APK Studio from passing the AppImageHub test for 2 years)

**Comment by vaibhavpandeyvpz** [comment]
This has been discussed earlier as APK Studio uses some other 3rd-party tools to fulfill its purpose which if bundled within APK Studio, would require repackaging of AppImage to update them. If this is a requirement, I would opt-out of AppImageHub. Having those dependencies specified by user allows them to swap out as per their requirement.

**Comment by probonopd** [comment]
OK, I understand. Well, at least the application doesn't just crash but at least does something (show a message), so I will leave it as is. Thanks @vaibhavpandeyvpz

**Pull request merged**
