### PR TITLE
Adds the option to pass custom update information

### PR DESCRIPTION
**Pull request by tilya**
If linuxdeployqt is called with the option -updateinformation=<update
string>, it passes that update string to appimagetool. Otherwise it uses
-g to guess (the original behavior).

### CODE REVIEW

**Comment by probonopd** [comment]
Thank you, a very useful contribution 👍

**Comment by probonopd** [comment]
Could you please update` README.md` accordingly as well?

**Comment by tilya** [comment]
I have also updated the README.md file. Is there something else I have missed?

**Comment by probonopd** [comment]
Thank you very much 👍

**Comment by tilya** [comment]
Thank you for merging :)

**Pull request merged**
