### PR TITLE
Improve glibc error message

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by probonopd** [comment]
Hi @patrickelectric you may have noticed the dicrepancy between the newest recommended glibc version and the newest we currently _accept_. That is because [OBS](https://build.opensuse.org/) uses a newer one than what we recommend.

Also, we don't want to promote the use of `-unsupported-...` flags. They are unsupported for a reason, and will produce AppImages that may fail the automated tests on AppImageHub.

**Comment by patrickelectric** [comment]
We are not promoting the usage of "-unsupported" glibc, the continuous build is a development one, right ? So this would help everybody that is developing with linuxdeploqt. It took some time to read the issue comments and figure out the necessary command to test linuxdeploqy, I can make the error message more sinister about `-unsupported` glic flag, but I believe that should be displayed.

**Comment by probonopd** [comment]
Yes, making it "more sinister" sounds good :+1:

**Comment by patrickelectric** [comment]
@probonopd 	please take a look if the message is 'sinister' enough.

**Comment by probonopd** [comment]
Yes, I think this 'sinister' enough :+1: 

But please be aware that the message should announce another glibc version, namely the one the oldest Ubuntu LTS release comes with (this is our policy); even though the actual threshold may be a bit higher currently (so that we don't break the current OBS setup as per common request).

Also changed the text a bit.

Please make sure it fits into a standard 80 characters wide terminal without reflowing.

**Comment by patrickelectric** [comment]
@probonopd Message updated, ubuntu 14.04 comes with glibc 2.19 and 18.04 with 2.27;

**Comment by probonopd** [comment]
If Ubuntu 14.04 comes with glibc 2.19 then it should print 2.19. We want to educate linuxdeployqt users to build on a build system no newer than the oldest still-supported Ubuntu LTS, because that is also what the AppImages will be tested against on https://github.com/AppImage/appimage.github.io.

**Comment by probonopd** [comment]
Sorry if I was not clear. We should _print_ the glibc version that the oldest still-supported Ubuntu LTS uses 2.19 but (at least if we are running on openSUSE) _silently accept_ whatever OBS is using (I think 2.26). (The latter can be dropped once the former is the same of a higher version).

**Comment by patrickelectric** [comment]
@probonopd Sorry, commit removed.

**Comment by patrickelectric** [comment]
@probonopd 	is something missing ?

**Comment by patrickelectric** [comment]
I'm just updating what we have in the master branch, not sure how can I test the distro that is running to select the correct glibc version. I thought that AppImage could run in any operating system and was not distro based.

**Comment by probonopd** [comment]
> I'm just updating what we have in the master branch, not sure how can I test the distro that is running to select the correct glibc version.

Not sure what you want to achieve there. I think what master currently does is the intended behavior.

> I thought that AppImage could run in any operating system and was not distro based.

The binaries contained inside an AppImage need to be compiled on a distribution older than or equal to the target system(s) where the application shall run.

**Pull request closed without merging**
