### PR TITLE
Fix for PrivateWidgets not deployed. closes #113

### LINKED ISSUE #113: PrivateWidgets library is not being deployed
Environment: [Qt 5.6.2 official] [Ubuntu 16.04 x64]

I'm deploying my Qt app [Xpiks](https://github.com/ribtoks/xpiks) with the [following script](https://github.com/Ribtoks/xpiks/blob/master/src/xpiks-qt/deploy_lin.sh) with _linuxdeployqt_.

When I start AppImage afterwards it segfaults when loading `main.qml` file. I have investigated that and it appears that `linuxdeployqt` does not deploy `libwidgetsplugin.so` (located at `$QT_BIN/qml/QtQuick/PrivateWidgets` path) to the resulting AppDir. So this needs to be done separately as it is not shown by the `ldd` but rather loaded by Qt in runtime (I suppose).

### PR DESCRIPTION
**Pull request by Ribtoks**
You're checking for the "QtWidgets" in the dependency libraries, but the Widgets library is called e.g. `libQt5Widgets.so.5` which makes comparison invalid

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @Ribtoks for your PR. #108 is blocking this from passing the tests at the moment. Will merge this once #108 is solved.

**Comment by probonopd** [comment]
This cannot merged in this form since it breaks the excludelist, which means that extraneous libraries would end up in the AppDir or AppImage which would break their compatibility.

**Comment by Ribtoks** [comment]
@probonopd This is GitHub automatically picking up the changes from my fork's master branch. I did not intend to send those changes.

Anyway, having excludelist hardcoded in the binary is not a wise choice if not to say more. Some other approach should be considered.

**Comment by probonopd** [comment]
Agree, but ideally let's do that in another PR (separate branch of your repository). Whenever you do additional changes to the `Ribtoks:master` branch, the will get appended to this PR until it is merged.

**Comment by Ribtoks** [comment]
Closing this PR as not valid anymore.

**Comment by probonopd** [comment]
Hi @Ribtoks I manually applied all changes but the last commit. Question: What is `findUsedModules` needed for? Do we really need a hardcoded list of all Qt modules? What if they add a module? What if we want to bundle Qt 4 or Qt 6?

**Comment by Ribtoks** [comment]
@probonopd

[serious] **Global answer:**
In worst case scenario (new Qt modules, missing in hardcoded list) some Qt translations will not get packed/deployed. No crashes in theory. `windeployqt` maintains this list so in each Qt release you might go to the source code of the latter and check if the modules are still there

[sarcasm] Qt 6 answer - then you will need to remove 90% of your code which you copy-pasted from _macdeployqt_ anyway which looks like `if string.StartsWith("libQt5")`

**Comment by probonopd** [comment]
@Ribtoks thanks for answering. It is still not clear to me for what purpose we need a hardcoded list of all Qt modules. Can you shed some light on this?

**Comment by Ribtoks** [comment]
@probonopd In `windeployqt` in such a way they create mask of all used modules (basically in O(n^2) by string matching) and later using that mask they combine few Qt translation files ("compiled" .qm files) into 1 file. For example, German translations for Qt Widgets, Qt Core, Qt Network ultimately will go into 1 file `qt_de.qm`. Is that clear now?

**Comment by probonopd** [comment]
@Ribtoks what is the advantage of combining multiple `.qm` files into one, in our case?

**Comment by Ribtoks** [comment]
@probonopd same as in "their" case? Just having less files to open/search, I guess. But I may be wrong of course. I guess the best place is to check is with windeployqt authors.
Cheers

**Pull request closed without merging**
