### PR TITLE
Added GitHub Action CI.

### PR DESCRIPTION
**Pull request by RICCIARDI-Adrien**
Here is an alpha version of the CI using GitHub Actions. Build is working (see https://github.com/RICCIARDI-Adrien/linuxdeployqt/runs/4833177835) and also deployment (see https://github.com/RICCIARDI-Adrien/linuxdeployqt/actions/runs/1704754459).

The following points are not working, I would like your thoughts before implementing them :
* I saw in the Travis CI build log that the PVS Studio license is expired. Does PVS studio still work with your license, and do you plan to still use PVS studio in the CI ?
* VERSION variable setting is not done yet (it was based on a Travis CI variable). Do you want to support this feature or all the new linuxdeployqt releases will be tagged "continuous" ?
* I had to comment the core dump enabling line `echo "/tmp/coredump" | sudo tee /proc/sys/kernel/core_pattern` because it was crashing the build, it this something important ?

### CODE REVIEW

**Comment by probonopd** [comment]
Hello, very cool! 
Thanks @RICCIARDI-Adrien for working on this. Very useful indeed.

To your questions:
* The PVS Studio license is expired, we can remove it or comment it out (in case we get a new license at some point in time)
* I am fine with setting the `VERSION` variable to the branch name (e.g., `continuous`) for now
* About the coredump, @TheAssassin do you remember?

**Comment by RICCIARDI-Adrien** [comment]
You're welcome !

Here are the changes :
* Commented the PVS Studio related code.
* Used the branch name as the `VERSION` variable value.
* Fixed the commit number not being present when running `linuxdeployqt --version`.
* Exported the `TRAVIS_BUILD_NUMBER` variable so it is displayed when running  `linuxdeployqt --version`.

**Comment by probonopd** [comment]
Do I need to do something to unblock it from this status?

image

**Comment by RICCIARDI-Adrien** [comment]
I will try to remove the Travis CI file, maybe this will unlock the CI step.

**Comment by RICCIARDI-Adrien** [comment]
This does not work, you may have to change some GitHub repository configuration, like disabling the Travis CI application.

**Comment by probonopd** [comment]
Can we please continue to use Ubuntu xenial? Ubuntu 20.04 is _much_ too new. The resulting AppImage would not even run on all still-supported Ubuntu LTS releases.

Here is how to run Ubuntu 16.04 on GitHub Actions:
https://github.com/actions/virtual-environments/pull/4313#issuecomment-950172940

**Comment by RICCIARDI-Adrien** [comment]
Sure, it is already using Ubuntu 16.04. The CI script won't even run on Ubuntu 18.04, I tried.

**Comment by RICCIARDI-Adrien** [comment]
Here are some information on how to disable Travis CI for this repository : https://remarkablemark.org/blog/2021/03/15/github-remove-travis-ci/#repository

**Comment by probonopd** [comment]
Fingers crossed!

**Comment by probonopd** [comment]
Looks like it got built successfully. This is **huge**! Thank you so much @RICCIARDI-Adrien :1st_place_medal:

**Comment by probonopd** [comment]
The git checkout does not seem to work on Pull Requests @RICCIARDI-Adrien. For example:

* https://github.com/probonopd/linuxdeployqt/pull/498
* https://github.com/probonopd/linuxdeployqt/pull/495

https://github.com/probonopd/linuxdeployqt/runs/4912172855?check_suite_focus=true#step:4:11

Maybe your manual workaround didn't consider the case of pull requests.
Do you have an idea how to make this work?

**Pull request merged**
