### PR TITLE
Remove the need for unset ... calls using AppRun file

### PR DESCRIPTION
**Pull request by probonopd**
https://github.com/probonopd/linuxdeployqt/issues/369

### CODE REVIEW

**Comment by PhysSong** [comment]
I think users may want to set `LD_LIBRARY_PATH` in some cases. For example, LMMS worked around the `unset` call by using extracted `linuxdeployqt` directly.
@probonopd Could you consider adding an option to override the default behavior, or just remove it?

**Comment by probonopd** [comment]
Thanks for your feedback @PhysSong. Can you point me to a concrete example where setting `LD_LIBRARY_PATH` is needed to run `linuxdeployqt`?

**Comment by PhysSong** [comment]
@probonopd Here:
https://github.com/LMMS/lmms/blob/8f4757ee3b8f1efe321a82d8b10f6bcf990233a9/cmake/linux/package_linux.sh.in#L132-L138
The WINE part is probably unneeded, but I'm not sure because I didn't write it.

**Comment by probonopd** [comment]
Ah, I get it now. Indeed, this is a valid concern. Thanks for pointing this out.

```
ERROR: ldd outputLine: "libcarlabase.so => not found"
ERROR: for binary: "/home/travis/build/PhysSong/lmms/build/LMMS.AppDir/usr/lib/lmms/libcarlarack.so"
ERROR: Please ensure that all libraries can be found by ldd. Aborting.
```

**Comment by probonopd** [comment]
A new continuous build containing this fix should appear in a few minutes.

**Pull request merged**
