### PR TITLE
Generate excludelist, CMake version

### PR DESCRIPTION
**Pull request by TheAssassin**
Thanks @patrickelectric for the script.

### CODE REVIEW

**Comment by probonopd** [comment]
Unfortunately this breaks on OBS, please see https://github.com/probonopd/linuxdeployqt/issues/272 and fix this, otherwise I need to revert.

**Comment by TheAssassin** [comment]
@probonopd since when do they use CMake to build linuxdeployqt?

**Comment by probonopd** [comment]
I dunno...

**Comment by TheAssassin** [comment]
Please don't threaten contributors before checking whether their code is responsible at all.

In this case, you're clearly in the wrong PR.

**Comment by probonopd** [comment]
Well. What happens if they switch to using CMake in the future? All I know is that before introducing this "let's pull the excludelist from the AppImages project" it worked. So reverting that logic will be my fallback if we can't fix it within a week. But I hope it can be fixed beforehand.

**Comment by TheAssassin** [comment]
The CMake build system is not the primary one. Also, you can't always satisfy everybody's use case. It is _their_ responsibility to make the build system work. It is not our job to verify that everything works for everybody at all times. At least in my opinion.

**Comment by TheAssassin** [comment]
Would you feel better if I added a big fat warning like "please consider using qmake" to the CMake script?

**Comment by probonopd** [comment]
> Would you feel better if I added a big fat warning like "please consider using qmake" to the CMake script?

That would be a nice way of saying "we don't really need it"?

**Comment by TheAssassin** [comment]
Why do you suddenly think that the CMake build system has no value? @azubieta and I use it for example, with our IDEs that support CMake but not qmake.

**Comment by probonopd** [comment]
>  "please consider using qmake"

gave me that impression ;-)
But hey, if it is useful for people, then it's fine with me - as long as it works.

**Comment by TheAssassin** [comment]
Well, you're obviously expecting somebody to use CMake instead of qmake to make "official" builds. Since CMake is (not yet) the official build system, we should notify users. That's all.

**Pull request merged**
