### PR TITLE
Add extra Qt plugins manually

### PR DESCRIPTION
**Pull request by vadrian89**
>Since ldd doesn't seem to detect Svg deployment I have added another argument which adds it explicitely.  
It only works for Qt5-based applications, i tested it on my application(Cumulus-qt) and it works, please look review / edit it.   
If you don't like it please add the option to forcefully copy svg library in case ldd fails to show the dependency for it.(I don't know why it doesn't show, it simply doesn't, I can send you screenshot if needed as proof).  

>Also there is an unused variable which I commented, you can see in the comparison.

New:  
The application will have an extra argument which will add aditional Qt libraries, people can use this to force aditional libraries which the application might miss, such as the SVG library in my previous case.  
- It takes a comma separated value list and will deploy the files after the initial deployment, it takes only libraries in the form as "libQt.." and it works only for Qt5 because it will append ".so.5" at the end.   
- It will not break the build if the library is not found, but a warning will be left to the packager.
- Warning will also be shown if the library mentioned cannot doesn't contain "libQt".   

Might have missed something so, when you can, please look at the code and let me know if something needs to be added.

### CODE REVIEW

**Comment by probonopd** [comment]
Can we make this a bit more generic, i.e., support more than just svg?

**Comment by vadrian89** [comment]
Want me to add a list of extra libraries to deploy?   
Example: -extra-libraries=libQt5Svg.so.5,libQt5Xml.so.5  

And those should be added to the list?

**Comment by probonopd** [comment]
Yes, I think this would be useful. What do others think?

**Comment by vadrian89** [comment]
I will try this to do it by the end of the month, been very busy lately and didn't had time to do anything, sorry.

**Comment by probonopd** [comment]
Still looking forward to it ;-)

**Comment by TheAssassin** [comment]
@vadrian89 any reason you close this without a comment?

**Comment by vadrian89** [comment]
@TheAssassin sorry for not commenting, didn't thought it would be necessary, I am preparing for another pull request with the changes mentioned me and @probonopd talked about in previous comments.

**Comment by TheAssassin** [comment]
You should rather re-use this PR. You can do so by force-pushing to the branch used for this PR.

**Comment by vadrian89** [comment]
>You can do so by force-pushing to the branch used for this PR. 

That's a new thing for me, need to check it out first, in the meantime is it ok to reopen this pull request?

**Comment by probonopd** [comment]
@vadrian89 
Add more commits by pushing to the __master__ branch on __vadrian89/linuxdeployqt__.

**Comment by vadrian89** [comment]
@probonopd

I messed up in my commits in trying to solve confflicts between your branch and mine, so sorry in advance when you will see the idiotic commits in my PR.

**Comment by probonopd** [comment]
> List of extra Qt libraries which should be deployed, separated by comma.

Is this about extra libraries such as libQt5Svg.so or about extra plugins? Because `linuxdeployqt` should figure out which Qt libraries are needed automatically. For plugins, I don't think that is possible.

**Comment by vadrian89** [comment]
From what I see deployplugins is getting called in main.cpp at line 424, this seems to me that it is getting called after libraries are deployed.  
Aswell, in the function deployplugins looks like the plugins are getting deployed based on the libraries in deploymentInfo.deployedLibraries.
Am I missing something?

**Comment by probonopd** [comment]
When deploying plugins, the libraries they depend on also get deployed.

And yes, currently the plugins to be deployed are determined by looking at which libraries get deployed, but as said above, this is not sufficient. It would be good to have the option to force deploy more plugins.

**Comment by vadrian89** [comment]
Ok, will look into it.

**Comment by probonopd** [comment]
An example for an application that would benefit from this:

https://github.com/probonopd/quassel/blob/773227a2accc9c282defdef5841c5db06c42ef6d/.travis.yml#L27-L28

**Comment by probonopd** [comment]
@vadrian89 still working on this?

**Comment by vadrian89** [comment]
I am confident that by the end of the week I will have a working commit.  
Don't have time to fully focus on it so that's why it takes a bit to finish.

**Comment by vadrian89** [comment]
I have a bit of dilemma, what should the plugins list contain in the argument?  
The relative path of the plugins, the name of the plugin, name of the module?
The path would be the most straightforward, for me:. 
-extra-plugins=sqldrivers/libqmsql.so,iconengines/libqsvgicon.so  
This way the developers are sure of exactly what gets deployed, we won't deploy unnecessary plugins as it is pretty straightforward.  
If we we go my the name of the plugins, such as libqmsql.so, we either will have to go through each directory until we find it or make a huge function which goes through if conditions until it deploys everything.... doesn't seem to ok, from my point of view.
If we go by the name of the module, I can add the paths to the modules entries and then the application can iterate through until every plugin is deployed, but the bad side is that we will sometimes will deploy multiple plugins which is just a waste of space(just like what the deployplugins function does now), which I dislike to do.....I think the app should not deploy unnecessary files.  
Any thoughts in this matter?

**Comment by vadrian89** [comment]
So I have decided to do the following, allow both plugin directory name and directory/plugin.so and here is the workflow:   
1. check if the plugin requested is a directory;
2. if it is a directory it will deploy that;
3. if it isn't, then it will try to deploy as an explicit plugin(directory/plugin.so).

What do you think? @probonopd & @TheAssassin

**Comment by probonopd** [comment]
Sounds good to me @vadrian89

**Comment by TheAssassin** [comment]
Sounds okay, but make sure it won't get too complex, please. I guess you can perform all checks with a single `stat()` call.

**Comment by probonopd** [comment]
TODO before merge: Make sure the long help string fits into the 80 wide default Ubuntu terminal

**Comment by vadrian89** [comment]
It seems it doesn't.

captura de ecran din 2017-12-02 16-00-32

**Comment by probonopd** [comment]
Thanks for checking @vadrian89 - can you please make the lines fit into that window, or use line breaks so that it looks decent? Thank you very much.

**Comment by vadrian89** [comment]
Will do

Pe 2 dec. 2017 4:40 p.m., "probonopd" <notifications@github.com> a scris:

**Comment by vadrian89** [comment]
I have formatted it, aswell as other lines(verbose and executable), let me know your opinion before I commit and push.

captura de ecran din 2017-12-02 17-12-44

**Comment by vadrian89** [comment]
Also this is with ":" before the newlines.  
Let me know which version you like best.
captura de ecran din 2017-12-02 17-15-03

**Comment by probonopd** [comment]
Thanks @vadrian89 I like the first version without the extra `:` best.

**Comment by probonopd** [comment]
Hello @vadrian89 we should add some documentation on how to use this in the README.md. Example conversation from IRC:

```
for macdeployqt, I've got a patch that makes it possible to deploy extra plugins that Qt doesn't know about. Is that possible with linuxdeployqt as well?
yes 
-extra-plugins=<list>
List of extra plugins which should be deployed, separated by comma
it was added in https://github.com/probonopd/linuxdeployqt/pull/152/files
the actual .so files, or folders where the plugins are stored?
i think the name.so should be enough
iirc, you can also specify directory/name.so
documentation is lacking here
```

It would be great if you could send a PR for `README.md`, ideally giving one or two examples. Thanks.

**Comment by vadrian89** [comment]
Sure thing!

**Pull request merged**
