### PR TITLE
shared: Update exclude list

### LINKED ISSUE #259: libfontconfig
I would like to include libfontconfig in my appimage.
Motive:
```
 ✘ patrick@dell  ~/Downloads/squashfs-root  export QT_DEBUG_PLUGINS=1                     
 patrick@dell  ~/Downloads/squashfs-root  ./program
ping.logger: qml true
ping.logger: ping.waterfallGradient true
ping.logger: ping.waterfall true
ping.logger: ping.logger true
ping.logger: ping.util true
ping.logger: ping.main true
QFactoryLoader::QFactoryLoader() checking directory path "/mnt/hd/Downloads/squashfs-root/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/mnt/hd/Downloads/squashfs-root/plugins/platforms/libqxcb.so"
Found metadata in lib /mnt/hd/Downloads/squashfs-root/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 330241
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/mnt/hd/Downloads/squashfs-root/platforms" ...
Cannot load library /mnt/hd/Downloads/squashfs-root/plugins/platforms/libqxcb.so: (/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var)
QLibraryPrivate::loadPlugin failed on "/mnt/hd/Downloads/squashfs-root/plugins/platforms/libqxcb.so" : "Cannot load library /mnt/hd/Downloads/squashfs-root/plugins/platforms/libqxcb.so: (/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var)"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
```

Same thing with [this one](https://github.com/sithlord48/atcore/releases/download/continuous/AtCore_Test_Client-x86_64.AppImage).

Any motive to not include it ? [Line.](https://github.com/probonopd/linuxdeployqt/blob/c01cf7727d24f04956815eac52105a574fa65077/tools/linuxdeployqt/shared.cpp#L476)

I'm running arch linux with the last version of this library.

### LINKED ISSUE #261: linuxdeployqt blacklists libfontconfig
There's this:

tools/linuxdeployqt/shared.cpp:        excludelist << "libasound.so.2" << "libcom_err.so.2" << "libcrypt.so.1" << "libc.so.6" << "libdl.so.2" << "libdrm.so.2" << "libexpat.so.1" << "libfontconfig.so.1" << "libgcc_s.so.1" << "libgdk_pixbuf-2.0.so.0" << "libgio-2.0.so.0" << "libglib-2.0.so.0" << "libGL.so.1" << "libgobject-2.0.so.0" << "libgpg-error.so.0" << "libICE.so.6" << "libkeyutils.so.1" << "libm.so.6" << "libnsl.so.1" << "libnss3.so" << "libnssutil3.so" << "libp11-kit.so.0" << "libpangoft2-1.0.so.0" << "libpangocairo-1.0.so.0" << "libpango-1.0.so.0" << "libpthread.so.0" << "libresolv.so.2" << "librt.so.1" << "libSM.so.6" << "libstdc++.so.6" << "libusb-1.0.so.0" << "libuuid.so.1" << "libX11.so.6" << "libxcb.so.1" << "libz.so.1";

But that leads to issues like this:

https://bugs.kde.org/show_bug.cgi?id=392307

"The latest 4.0 appimage fails to start just like in bug 382944 and using QT_DEBUG_PLUGINS=1 reveals the same as in the attachment:

QLibraryPrivate::loadPlugin failed on "/tmp/.mount_appimaY4YLSz/usr/plugins/platforms/libqxcb.so" : "Cannot load library /tmp/.mount_appimaY4YLSz/usr/plugins/platforms/libqxcb.so: (/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var)""

On ArchLinux

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #259 
Fix #261  
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by TheAssassin** [comment]
I thought the list was auto updated during the Travis build?

This PR's all yours, @probonopd.

**Comment by probonopd** [comment]
> I thought the list was auto updated during the Travis build?

I don't understand what you mean @TheAssassin. I keep this list in the C source code updated by hand, so that it is (more or less) in sync with https://github.com/AppImage/AppImages/blob/master/excludelist.

**Comment by TheAssassin** [comment]
I see. @probonopd I would then vote for automatically editing this list in some way on Travis CI to ensure it is up to date.

**Comment by probonopd** [comment]
Might be worth doing - although I have no clue how...

**Comment by TheAssassin** [comment]
@probonopd it isn't that hard. We can have CMake download the list, perform some string manipulations, and provide it as a compiler definition or something like that. We could also run a bash script preparing the list by generating some header file in the build directory.

**Comment by TheAssassin** [comment]
Oh, right, this is a qmake project... well I'm sure there's a way to do it with qmake as well.

**Comment by patrickelectric** [comment]
@TheAssassin @probonopd done in #263

**Pull request merged**
